%% Step 0

clc;
clear;
close all;

N = 10000;
n = 0:1:N -1;
isStep = 1;
Nfft = N/2;
Nw = 50;
h = ones(1,Nw);
plotFlag = 1;

%% Step 1

% Comp 1
f1 = 0.15;
x1 = cos(2 * pi * f1 * n);

% Comp 2
f2 = 0.38;
x2 = zeros(1,N);
x2(5000:8000) = cos(2 * pi * f2 * (1:3001));

% Comp 3
impulseResponse = my_filter; % I get the filter generated by the tool
wgn = randn(1,N); % wgn
x3 = filter(impulseResponse,wgn); % Filtering

% Comp 4
% To create a quadratic chirp, the derivative of the instantaneous phase -
% the equation inside the cos - must be the integral of a parabola, vertex
% = (-b/2a, -(b^2-4ac)/4a)
% from analysis, vertex is in (6500,0.45)
c = 0;
a = -4 * 0.45 / (169e6);
b = -13000 * a;
x4 =  cos((2* pi) * a*n.^3/3 + (2* pi) * b*n.^2/2 + c*n);


%% Sum and analysis

x  = x1 + x2 + x3 + x4;

Px = my_spectrogram(x, isStep, Nfft, h, plotFlag);