%% testTopologyMultipleTimes
% function [sol_algorithm, topology] = testTopologyMultipleTimes (trf_m, number_nodes,n_tries, n_delta, check, probability)

function [sol_algorithm, topology, min_connected] = testTopologyMultipleTimes (trf_m, number_nodes,n_tries, n_delta, check, probability)

if nargin == 5
    n_check = check;
    p = 0.1;
elseif nargin == 6
    n_check = check;
    p = probability;
else
    n_check = 3;
    p = 0.1;
end
    
    connected = zeros(1,n_tries);

for count=1:n_tries
    [bij, arcs] = generate_flow_matrix_bis(number_nodes, n_delta, p, n_check, trf_m);
    [flow_matrix_bij, max_flow_bij] = route_by_shortest_path (bij, arcs, number_nodes, trf_m);
    bij_array(:,:,count) = flow_matrix_bij;
    array_bij(count) = max_flow_bij;
    
    bins = conncomp (digraph(bij));
    if sum(bins) == number_nodes
        connected(count) = 1;
    end
end

s = sprintf('n of connected topologies generated by the algorithm = %.0f', sum(connected));
disp(s);

sol_algorithm = array_bij;
I = find(min(array_bij) == array_bij, 1 );

if (sum(connected) > 0)
I = find(min(array_bij(find(connected>0))) == array_bij, 1 );
else
I = find(min(array_bij) == array_bij, 1 );
end    
min_connected = I;

topology = bij_array (:,:,I);

% figure, plot(digraph(topology))